version: '3.1'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-notebook
    ports:
      - "8880:8888"

  lab:
    build:
      context: .
      dockerfile: Dockerfile-lab
    ports:
      - "8881:8888"