FROM python:3.12
WORKDIR /app
COPY . .

RUN pip install notebook

ENV TOKEN=$NOTEBOOKS_TOKEN

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token='${TOKEN}'"]
EXPOSE 8888