FROM python:3.12
WORKDIR /app
COPY . .

RUN pip install notebook

RUN pip install --upgrade pip ipython ipykernel

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
EXPOSE 8888