FROM python:3.12
WORKDIR /app
COPY . .

RUN pip install jupyterlab

ENV TOKEN=$LABS_TOKEN

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token='${TOKEN}'"]
EXPOSE 8888